apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resourceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart-name: "{{ .Chart.Name }}"
    chart-version: "{{ .Chart.Version }}"
    app: "{{ .Values.resourceName }}-service"
    app.kubernetes.io/name: {{ .Values.dashboard.name | default .Release.Name }}
    app.kubernetes.io/version: {{ .Values.tag }}
    app.kubernetes.io/component: {{ .Values.dashboard.component | default "Frontend" }}
    app.kubernetes.io/part-of: {{ .Values.dashboard.partOf | default .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/created-by: {{ .Values.dashboard.createdBy | default .Release.Service }}
    helm.sh/chart-name: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version | replace "+" "_" }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  ports:
    - name: web
      port: {{ .Values.port }}
    - name: status
      port: 8180
    {{- if (not (eq (toString .Values.prometheus_enabled) "false")) }}
    - name: prometheus
      port: 9113
    {{- end }}
  selector:
    app: {{ .Values.resourceName }}
